<?php


namespace backend\controllers;


use common\models\Client;
use common\models\Order;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AppAdmin extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                        'roles'=>['?']
                    ],
                    [
//                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $order        = new Order();
        $client =  new Client();

        Yii::$app->params['typePackages'] = $typePackages;

        Yii::$app->params['totalPack'] = $totalPack;

        Yii::$app->params['totalCost'] =  $totalCost;

        Yii::$app->params['totalSize'] =  $totalSize;

        Yii::$app->params['totalWeight'] =  $totalWeight;

        Yii::$app->params['avgCost '] =   $avgCost ;

        Yii::$app->params['client'] = $clients;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}